### PR TITLE
Added Alligator board variant

### PR DESCRIPTION
**Pull request by MarcoAntonini**
Alligator board src for next release see RepRapFirmware pull request #127 (https://github.com/dc42/RepRapFirmware/pull/127)

### CODE REVIEW

**Comment by dc42** [comment]
I've accepted this request. However, it would be better if you use your own VID/PID combination instead of the one allocated to the Duet. If you don't already have one, you can request a VID/PID combo for an open source project at http://pid.codes/.

**Comment by MarcoAntonini** [comment]
I just requested a new pid, when it will be approved I will change it.
Thanks!

**Comment by dc42** [comment]
Let me know when it comes through and what it is because I will need to update the Windows device driver to include it.

**Comment by MarcoAntonini** [comment]
Ok, the Pid for Alligator has been accepted and allocated as 1209:AB3D (merged request #3)

**Pull request merged**
