### PR TITLE
Change Alligator USB PID 1209:AB3D

### PR DESCRIPTION
**Pull request by MarcoAntonini**

### CODE REVIEW

**Comment by MarcoAntonini** [comment]
Reference to commit #2

**Comment by dc42** [comment]
Please can you test the updated Windows device driver at https://dl.dropboxusercontent.com/u/19369680/DuetDriverFiles.zip with Alligator before I release it.

**Comment by MarcoAntonini** [comment]
Thanks, it Work!


I noticed some errors in RepRapFirmware eclipse settings that do not allow compilation for alligator. I'll fix them.

**Comment by dc42** [comment]
That's OK, I've already changed my eclipse settings so that the
Alligator version builds. I will commit that change along with 1.19RC2
source code, later tonight I hope.

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486

**Pull request merged**
